import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';

import MyNavbar from './navbar';
import MyFooter from './footer';
import { ModalBody } from 'react-bootstrap';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <MyNavbar />
      {children}
      <MyFooter />
      </body>
    </html>
  )
}
